### ISSUE TITLE
Archive/deprecate this repo?

### ISSUE THREAD

**Issue by uumaro** [keroserene/go-webrtc#109]
The reason for creating go-webrtc was to support the development of [Snowflake](https://trac.torproject.org/projects/tor/wiki/doc/Snowflake). But since October 2019, Snowflake [no longer uses go-webrtc](https://bugs.torproject.org/28942), instead using [pion/webrtc](https://github.com/pion/webrtc). That means the maintainers of go-webrtc are no longer paying much attention to it.

Should we archive this repo, or add a note that it is no longer actively maintained? Hand over maintainership to someone else? As evidenced by the [issues page](https://github.com/keroserene/go-webrtc/issues), there are uses besides Snowflake; what would they like to see happen?

**Comment by gabelula** [comment]
I think it would makes sense to add a note to the README and the home of the repo that it is no longer mantained and that if somebody want to start mantaining it then please step up.
