### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by arlolra** [keroserene/go-webrtc#30]

**Comment by mjena** [comment]
Hi @arlolra,
Is there any way, I can build this package for windows?


thanks,
Mahesh

**Comment by arlolra** [comment]
Support is planned, but still TODO.

You'd need to adapt the script in #51 to build the library and then write package config file similar to the other webrtc-*.pc

**Comment by arlolra** [comment]
This is being worked on in #57 so closing as duplicate.
