### ISSUE TITLE
OnIceComplete is to be deprecated in the native API

### ISSUE THREAD

**Issue by whatisgravity** [keroserene/go-webrtc#31]
I noticed this comment in the code, what is planned to replace this function call if it is being deprecated. I may be able to implement the new method but I'm not sure what replaces OnIceComplete()

**Comment by arlolra** [comment]
I assume `OnIceGatheringStateChange`, see #27

**Comment by whatisgravity** [comment]
Ill close this since that ticket does cover it. Thanks.
