### ISSUE TITLE
Fix all the leaks

### ISSUE THREAD

**Issue by arlolra** [keroserene/go-webrtc#35]
https://travis-ci.org/keroserene/go-webrtc/jobs/111552745

**Comment by amitu** [comment]
May be not all leaks are fixed. I have a process that is connected to other via webrtc data channel, and they are pinging each other every second or say. Its grown from 70MB to 90MB in two hours. 

I am looking if the leak is on my side, but haven't found anything so far.

**Comment by arlolra** [comment]
To be clear, this was leaks as reported by ASAN.

I'm pretty sure there're still application level leaks like,
https://github.com/keroserene/go-webrtc/blob/master/peerconnection.cc#L197-L199

and,
https://github.com/keroserene/go-webrtc/blob/master/peerconnection.cc#L180-L182

We probably need to [set a finalizer](https://golang.org/pkg/runtime/#SetFinalizer) to release that memory when it's no longer needed.  I'll open a bug for that.

**Comment by arlolra** [comment]
@amitu But if you could provide a test case or look at snapshot of your heap to find out what exactly is being retained, that would be helpful.  Thanks for reporting!

**Comment by amitu** [comment]
@arlolra, I will do that over the weekend, and let you know.
