### ISSUE TITLE
golang 1.6 cgo compatibility

### ISSUE THREAD

**Issue by arlolra** [keroserene/go-webrtc#36]
https://golang.org/doc/go1.6#cgo

We're seeing a couple `runtime error: cgo argument has Go pointer to Go pointer`

**Comment by keroserene** [comment]
Short term workaround is to just set this environment variable which disables the runtime complainer:
`export GODEBUG=cgocheck=0`

Which allows the chat demo to work. But actually fixing this should probably be high priority (as I'm now running into this new mysterious failure in Snowflake after updating to Go 1.6, so I'll look into it)

**Comment by keroserene** [comment]
Awesome :+1:
