### ISSUE TITLE
Controlling the ICE Candidates?

### ISSUE THREAD

**Issue by lostinblue** [keroserene/go-webrtc#37]
I am interested in using two onion services to initiate webRTC connections over websockets. I have setup onion routed websockets connections but I'm not sure how best to only create a ice candidate for the onion address and nothing else. Would I need to modify the C++ library? Would it be better to convert more of the C++ to golang? Or is there an easier way than both those routes? I appreciate your insight since you seem to understand this subject well.

**Comment by keroserene** [comment]
I'm not clear what you're asking -- by "using two onion services to initiate webRTC connections over websockets", do you mean setting up a WebRTC peer connection between two onion services which have a separate websocket channel between them as rendezvous, or do you mean providing an "onion rendezvous service using websocket" which could act as the signalling channel to setup WebRTC peer connections between arbitrary peers? Or something else?

ICE candidates are only gathered from the host trying to be a WebRTC peer. If you only want to see what the candidates are, the normal `CreateOffer` will already generate SDP messages containing the ICE candidates you're after. Not sure why you'd need to modify the C++ library, unless I'm misunderstanding - hope this helps.
