### ISSUE TITLE
Support for 32-bit Linux

### ISSUE THREAD

**Issue by kc87654321** [keroserene/go-webrtc#38]
ubuntu16, linux32
i get error:
/home/wd/go/go/bin/go build -i [/home/wd/go/work/src/demo]
# github.com/keroserene/go-webrtc

/usr/bin/ld: cannot find -lwebrtc-linux-386-magic
collect2: error: ld returned 1 exit status

**Comment by arlolra** [comment]
Unfortunately, we've only included the magic for 64-bit architectures (see `lib/`) so far.

Support for 32-bit Linux was added as part of https://trac.torproject.org/projects/tor/ticket/19001 (93f5259d, 3a7f6aed7) though.  Describing the process will be easier once #23 is closed.

**Comment by kc87654321** [comment]
chao,arlolra ,Taks very mach, ,have any web than can download the lwebrtc-linux-386-magic.a ?

**Comment by traumschule** [comment]
Ran into this on debian buster 32-bit for https://trac.torproject.org/projects/tor/wiki/doc/Snowflake#Option2standalone:
```
~/go/src/git.torproject.org/pluggable-transports/snowflake/proxy-go$ torsocks go get                                                                                                  
# github.com/keroserene/go-webrtc
/usr/bin/ld: cannot find -lwebrtc-linux-386-magic
collect2: error: ld returned 1 exit status
```

**Comment by uumaro** [comment]
Is there any reason why we don't include a prebuilt linux-386 library by default? Since the porting work is done, it ought to be as simple as `GOOS=linux GOARCH=386 ./build.sh`.

**Comment by uumaro** [comment]
@kc87654321, @traumschule, does the library built in #103 work for you?

**Comment by arlolra** [comment]
> Is there any reason why we don't include a prebuilt linux-386 library by default?

Nope
