### ISSUE TITLE
Memory collision / leak for some cases of multiple DataChannels

### ISSUE THREAD

**Issue by keroserene** [keroserene/go-webrtc#41]
Discovered while working on snowflake's multiplexing.
- Everything is fine when I create one PeerConnection with a DataChannel.
- Everything is also fine when I create multiple PeerConnections, so long as only one has tried creating a DataChannel.
- Everything is not fine as soon as there are >= 2 DataChannels. The first DataChannel, even if live and exchanging bytes correctly, immediately ceases to exchange bytes correctly as soon as `NewDataChannel` is called. Closing / cleanup also does not work correctly at this point (while previously it would) either. This is replicable.

Looking into this more now.

**Comment by arlolra** [comment]
That seems to fix it for me ... but I'm not sure why that's necessary.

Can you confirm?

**Comment by keroserene** [comment]
Confirmed, that does fix it! Awesome.

Strange that we need a global index increment here.
Oh, I think I know what's going on. It's in the method signatures, i.e.
`func (m CGOMap) Set(...`

I believe it should be by reference, since these methods mutate the struct:
`func (m *CGOMap) Set(...`

Can you verify if that works (without the global counter)? :)

**Comment by arlolra** [comment]
Yup, LGTM :)

**Comment by arlolra** [comment]
https://golang.org/doc/faq#methods_on_values_or_pointers
