### ISSUE TITLE
demo/chat/chat.go not working

### ISSUE THREAD

**Issue by mjena** [keroserene/go-webrtc#49]
the text size which need to be pasted on the peer side is more than 1024 which is not able to received in reader := bufio.NewReader(os.Stdin) object whose maximum length can be 1024.

Is there any other way to paste the message to peer side?

**Comment by arlolra** [comment]
https://golang.org/src/bufio/bufio.go says, `defaultBufSize = 4096`

You can always edit the demo to use `NewReaderSize` and specify whatever you want.

**Comment by mjena** [comment]
may be i was not clear on my description:
When I copy the text from peer1 and paste it in peer2, in Peer2, the whole text is not able to paste and it does not work anything after that.
I imagine, it may be because of the special characters that are part of the text from peer1.

Is there another way of testing it or do I need to do something different here?

Please check the attached screenshot for more clarification!!

![peer1](https://cloud.githubusercontent.com/assets/22209799/20333692/416d985e-abda-11e6-99b0-de366bed2313.png)
![peer2](https://cloud.githubusercontent.com/assets/22209799/20333693/417c61d6-abda-11e6-8dd5-c3fffb53eaee.png)

**Comment by arlolra** [comment]
The default for `bufio.NewReader(os.Stdin)` according to that link is `4096`, not `1024`.  Which version of golang are you running?

Can you confirm that the offer you're copying is even greater than 1024?  Try pasting in a text editor and seeing if you get what expected there first.  When I tried it, it was less than 800 chars.

You can edit chat.go and replace the `bufio.NewReader(os.Stdin)` with `bufio.NewReaderSize(os.Stdin, 4096)`, or whatever you want.

You can also try opening the chat.html file in your browser and pasting the offer there.

But, to be clear, I think maybe your copy buffer is limited or something weird like that, and there's nothing wrong with the chat.go, at least as far as I can tell.

**Comment by mjena** [comment]
hi,
I can send the offer and answer to each other client now with some workaround :D, but I am not able to send chat to other peer.

My last few logs (in both the peers) are:

Data Channel Opened!
------------ chat enabled! ------------
<after this, i am entering the message in one peer but its not receiving at the other peer>

I assume the log above establish a connection between 2 peers and channel.OnOpen() function is called.
but when I am sending the message, there is no call for channel.OnMessage.

Let me know, if I need to add anymore configuration for the message to pass between the peers using datachannel

**Comment by arlolra** [comment]
Can I see the diff you needed to make it work?

Also, can you provide more information about your system?  Platform, arch, etc.

**Comment by mjena** [comment]
Instead of copy-paste, I sent the offer message to a server (kinda relay) and then that server sent the message as it is to other peer, similarly the answer is also travelled through the server and now the channel is established between these 2.
Both my peers are running on MAC OSx.

I put few debug logs in your code and found, when I send a message in chat, the call is going till CGO_Channel_Send() function and then i could not able to debug further for dc->Send(). :(

Can you please help?

**Comment by mjena** [comment]
never mind, i found out the solution for this.
1. the 1024 character limitation is with stdin of MAC system. unfortunately my Offer/Resource string characters were more than 1024 characters thats why i was not able to paste them on terminal.
2. for dc.Send(), there was some issue with channel object that I was using for the OnMessage() callback.

Thanks a lot for the help! :)

**Comment by arlolra** [comment]
Glad it's working for you.
