### ISSUE TITLE
DataChannel with unreliable and unordered modes

### ISSUE THREAD

**Issue by shazow** [keroserene/go-webrtc#53]
Right now the DataChannels are always created in in reliable and ordered modes, even if `webrtc.Init{Ordered: false}` is given.

Additionally, it seems that `MaxPacketLifeTime` and `MaxRetransmits` are also being ignored (both end up with 65535).

Any suggestions before I dive deeper into this? (Any of this by design? Any gotchas to look for?)

**Comment by arlolra** [comment]
> Any of this by design?

No, it's just that we've pretty much been implementing features as we need them.

**Comment by DylanJ** [comment]
@shazow @arlolra - I've implemented a portion of the missing config passing which prevented us from setting Ordered and MaxRetransmit* options on the DataChannel over at `https://github.com/DylanJ/go-webrtc` - I'm happy to clean it up to get it merged upstream. 

Previously you would create a datachannel with 

```go
dc := peerconnection.CreateDataChannel(
  "some-label",
  webrtc.Init{options which were ignored},
)
```

In my branch you can do:
```go
dc := peerconnection.CreateDataChannel(
  "some-label",
  webrtc.Ordered(false),
  webrtc.MaxRetransmits(0),
)
```

**Comment by arlolra** [comment]
Sure, doesn't hurt to open a PR.

**Comment by cruciux** [comment]
@DylanJ @arlolra please please add this, it'll be super cool to be able to use an unordered data channel! I would contribute myself but don't know enough yet..

**Comment by DylanJ** [comment]
@cruciux - You can use the code in this PR: https://github.com/keroserene/go-webrtc/pull/59

**Comment by arlolra** [comment]
#59 was merged.
