### ISSUE TITLE
Run chat demo on macOS got killed

### ISSUE THREAD

**Issue by Akagi201** [keroserene/go-webrtc#64]
```
go-webrtc git/master
❯ go run demo/chat/chat.go
signal: killed
```

It works on Linux.

So I doubt that the webrtc static lib on mac is broken or something wrong.

**Comment by arlolra** [comment]
Continuous integration os macOS is passing,
https://travis-ci.org/keroserene/go-webrtc/jobs/215717082

and testing locally, the demo worked as expected.

Can you say more about your system?  And, is it repeatable?

**Comment by Akagi201** [comment]
Yes, It got killed every time.
![image](https://cloud.githubusercontent.com/assets/1207959/25030038/bb59a11e-20f4-11e7-87b3-d384707c0080.png)

**Comment by arlolra** [comment]
What version of go are you using?  How much free memory is available on your system?

It's not segfaulting; something is killing the build, which may mean you're OOM.  Though with 16gigs, that'd be quite the feat.

**Comment by Akagi201** [comment]
* Go version 1.8 (installed via [gvm](https://github.com/moovweb/gvm)), BTW, I also use go1.8 on linux.
* I reboot my mac, and run again, I still got `signal: killed`.
![image](https://cloud.githubusercontent.com/assets/1207959/25031082/cf8302a4-20fc-11e7-9517-c73f3dc74059.png)

**Comment by arlolra** [comment]
Hmm, maybe something to do with https://github.com/golang/go/issues/19734

Can you try some of the suggestions there?

**Comment by Akagi201** [comment]
Thanks. go1.81 works on macOS.
