### ISSUE TITLE
Great job! is it still alive? integrate with latest webrtc native codes?

### ISSUE THREAD

**Issue by leslie-qiwa** [keroserene/go-webrtc#74]
First of all, thanks for the great work!!!

Seems like not many check in, so just wonder what the future of this repo is, and any plan to integrate with the latest webrtc native codes?

**Comment by arlolra** [comment]
Yes, it's still alive; it's just not anyone's job to maintain it so finding time is hard.

> any plan to integrate with the latest webrtc native codes?

First priority is merging the open pull requests but, eventually, yes, we will bump to the latest branch.

**Comment by arlolra** [comment]
The tip of master is now at branch-heads/64
