### ISSUE TITLE
chat demo build failed

### ISSUE THREAD

**Issue by jiangsuwwj1** [keroserene/go-webrtc#84]
when i run 'go run demo/chat/chat.go', error occours as follows:

root@ubuntu:/opt/gopath/src/github.com/keroserene/go-webrtc# go run demo/chat/chat.go
/# github.com/keroserene/go-webrtc
./lib/libwebrtc-linux-amd64-magic.a(stringencode.o): In function `rtc::tokenize(std::string const&, char, std::vector<std::string, std::allocator<std::string> >*)':
stringencode.cc:(.text._ZN3rtc8tokenizeERKSscPSt6vectorISsSaISsEE+0x264): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
./lib/libwebrtc-linux-amd64-magic.a(stringencode.o): In function `rtc::tokenize_with_empty_tokens(std::string const&, char, std::vector<std::string, std::allocator<std::string> >*)':
stringencode.cc:(.text._ZN3rtc26tokenize_with_empty_tokensERKSscPSt6vectorISsSaISsEE+0x25f): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
./lib/libwebrtc-linux-amd64-magic.a(stringencode.o): In function `rtc::tokenize(std::string const&, char, char, char, std::vector<std::string, std::allocator<std::string> >*)':
stringencode.cc:(.text._ZN3rtc8tokenizeERKSscccPSt6vectorISsSaISsEE+0x3e9): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
stringencode.cc:(.text._ZN3rtc8tokenizeERKSscccPSt6vectorISsSaISsEE+0x401): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
./lib/libwebrtc-linux-amd64-magic.a(stringencode.o): In function `rtc::tokenize_first(std::string const&, char, std::string*, std::string*)':
stringencode.cc:(.text._ZN3rtc14tokenize_firstERKSscPSsS2_+0x152): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
./lib/libwebrtc-linux-amd64-magic.a(stringencode.o):stringencode.cc:(.text._ZN3rtc5splitERKSscPSt6vectorISsSaISsEE+0x25f): more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
collect2: error: ld returned 1 exit status

Here is my environment:
root@ubuntu:/opt/gopath/src/github.com/keroserene/go-webrtc# go version
go version go1.8.3 linux/amd64 

root@ubuntu:/opt/gopath/src/github.com/keroserene/go-webrtc# go env
GOARCH="amd64"
GOBIN="/opt/gopath/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build975447664=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

additionally i find this archive can work. 
`52280a1ecdfbfc0557a962ff832dbf5632122a35`

**Comment by arlolra** [comment]
Which version of gcc are you using?

**Comment by jiangsuwwj1** [comment]
[root@tosa1-jcy72 ~]# which gcc
/usr/bin/gcc
[root@tosa1-jcy72 ~]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by jiangsuwwj1** [comment]
The problem is that gcc version is not match. when i switch gcc to 7.2.1, problem is solved. 
Thanks a lot.
