### ISSUE TITLE
Cache the GCC-5 Dependency in circle.yml

### ISSUE THREAD

**Issue by keroserene** [keroserene/go-webrtc#9]
Ever since the codebase began using cgo-enabled subpackages, circle builds would fail if GCC is version 4.9. (Previously it was fine)

I've managed to work around this by including
```
- sudo apt-get update; sudo apt-get install gcc-5; sudo apt-get install g++-5
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
```
in the dependencies: pre: section, which fixed the build.

However, this apt-get's thing adds about a minute to the build...
Would be nice to have a way to cache it on our circle container.

**Comment by arlolra** [comment]
Closing since we aren't using CircleCI anymore.
